/**
 * What actually depends on a journal entry.
 *
 * ── Why this is a registry rather than a function with a long switch ─────────
 * Every module that generates or consumes journals is a potential dependency,
 * and the set grows. A hand-written switch is correct the day it is written;
 * the next module that posts to the ledger is the one nobody remembers to add,
 * and the failure is silent — an entry reports "no dependencies" and is
 * overwritten underneath a record derived from it.
 *
 * So each probe is registered as a value. Adding a module means adding a probe
 * next to it, and `journalDependencies.test.ts` asserts that every store which
 * carries a `journalEntryId` has one.
 *
 * ── Modules Ledgora does not have yet ────────────────────────────────────────
 * The requirement lists bank reconciliation, payroll and settled AR/AP
 * allocation as blockers. Ledgora has no bank-reconciliation or payroll module
 * today, and AR/AP settlement is expressed through payment and receipt
 * allocations, which ARE probed below. The two absent subsystems are declared
 * here as registered-but-inactive probes rather than omitted: an empty result
 * from a named probe is a fact ("no such module"), whereas leaving them out
 * would silently claim the question was asked. When either module lands, its
 * probe body is the only thing that changes.
 */
import type { JournalDependency } from '@/lib/journalAmendment';
import { useInvoiceStore } from '@/store/invoiceStore';
import { useBillStore } from '@/store/billStore';
import { usePaymentStore } from '@/store/paymentStore';
import { useReceiptStore } from '@/store/receiptStore';
import { useCreditNoteStore } from '@/store/creditNoteStore';
import { useInventoryStore } from '@/store/inventoryStore';
import { useFixedAssetStore } from '@/store/fixedAssetStore';
import { useJournalVoucherStore } from '@/store/journalVoucherStore';
import { useTaxPeriodStore } from '@/store/taxPeriodStore';

export interface DependencyProbe {
  /** Stable id, used by the coverage test and for diagnostics. */
  id: string;
  /** What this probe looks at, in one phrase. */
  describes: string;
  /** Returns every dependency the probe finds for this entry. */
  probe: (entryId: string, entryDate: string) => JournalDependency[];
}

/**
 * A journal generated BY another module.
 *
 * Blocks journal-level editing outright, and says where the correction belongs.
 * Reversing-and-replacing here would be no better than overwriting: both leave
 * the journal disagreeing with the document that produced it, and the document
 * is the thing the business actually reasons about. The correction has to
 * happen at the source, which then regenerates its own posting.
 */
function ownedBySource(
  sourceType: string,
  module: string,
  id: string,
  label: string,
): JournalDependency {
  return {
    kind: 'source_document',
    severity: 'blocks',
    sourceType,
    sourceId: id,
    sourceLabel: label,
    message: `This journal was generated by ${label}. Correct the ${sourceType.toLowerCase()} instead — editing the journal on its own would leave the two disagreeing.`,
    correctAt: { module, documentId: id, label },
  };
}

/** A record DERIVED from the entry, which a direct overwrite would invalidate. */
function derivedRecord(
  kind: JournalDependency['kind'],
  sourceType: string,
  id: string,
  label: string,
  detail: string,
): JournalDependency {
  return {
    kind,
    severity: 'requires_reversal',
    sourceType,
    sourceId: id,
    sourceLabel: label,
    message: `${label} was derived from this entry. ${detail}`,
  };
}

export const DEPENDENCY_PROBES: readonly DependencyProbe[] = [
  {
    id: 'tax-period',
    describes: 'Locked, filed or prepared tax periods covering the entry date',
    probe: (_entryId, entryDate) => {
      const periods = useTaxPeriodStore.getState().periods.filter(
        (p) => entryDate >= p.periodStart && entryDate <= p.periodEnd,
      );
      return periods.flatMap<JournalDependency>((period) => {
        const label = `Tax period ${period.periodStart} – ${period.periodEnd}`;
        if (period.status === 'filed' || period.status === 'locked') {
          return [
            {
              // A filed return is a regulatory record; a locked period is a
              // closed book. Neither may be altered by a journal editor —
              // reopening is a separate, separately-authorized act.
              kind: period.status === 'filed' ? 'filed_tax_return' : 'locked_period',
              severity: 'blocks',
              sourceType: 'Tax period',
              sourceId: period.id,
              sourceLabel: label,
              message: `${label} is ${period.status}. Reopen the period through period management before correcting entries dated inside it.`,
            },
          ];
        }
        if (period.status === 'prepared') {
          return [
            derivedRecord(
              'filed_tax_return',
              'Tax period',
              period.id,
              label,
              'It is prepared for filing, so the return would no longer match a direct overwrite.',
            ),
          ];
        }
        return [];
      });
    },
  },
  {
    id: 'invoice',
    describes: 'Sales invoices and their recorded payments',
    probe: (entryId) => {
      const { invoices } = useInvoiceStore.getState();
      const found: JournalDependency[] = [];
      for (const invoice of invoices) {
        if (invoice.journalEntryId === entryId) {
          found.push(ownedBySource('Sales invoice', 'invoices', invoice.id, `sales invoice ${invoice.invoiceNumber ?? invoice.id}`));
        }
        for (const payment of invoice.payments ?? []) {
          if (payment.journalEntryId === entryId) {
            found.push(
              ownedBySource('Invoice payment', 'invoices', invoice.id, `a payment recorded against invoice ${invoice.invoiceNumber ?? invoice.id}`),
            );
          }
        }
      }
      return found;
    },
  },
  {
    id: 'bill',
    describes: 'Supplier bills',
    probe: (entryId) =>
      useBillStore
        .getState()
        .bills.filter((b) => b.journalEntryId === entryId)
        .map((b) => ownedBySource('Bill', 'bills', b.id, `bill ${b.billNumber ?? b.id}`)),
  },
  {
    id: 'payment',
    describes: 'Payments and their AR/AP allocations',
    probe: (entryId) => {
      const found: JournalDependency[] = [];
      for (const payment of usePaymentStore.getState().payments) {
        if (payment.journalEntryId === entryId || payment.reversalJournalEntryId === entryId) {
          found.push(ownedBySource('Payment', 'payments', payment.id, `payment ${payment.paymentNumber ?? payment.id}`));
        } else if ((payment.allocations ?? []).length > 0 && payment.journalEntryId === entryId) {
          /* Settled AR/AP: the allocation was computed from this posting. */
          found.push(
            derivedRecord(
              'ar_ap_allocation',
              'Payment allocation',
              payment.id,
              `Allocations on payment ${payment.paymentNumber ?? payment.id}`,
              'Overwriting the entry would change amounts those allocations settled against.',
            ),
          );
        }
      }
      return found;
    },
  },
  {
    id: 'receipt',
    describes: 'Customer receipts and their allocations',
    probe: (entryId) =>
      useReceiptStore
        .getState()
        .receipts.filter((r) => r.journalEntryId === entryId || r.reversalJournalEntryId === entryId)
        .map((r) => ownedBySource('Receipt', 'receipts', r.id, `receipt ${r.receiptNumber ?? r.id}`)),
  },
  {
    id: 'credit-note',
    describes: 'Credit notes',
    probe: (entryId) =>
      useCreditNoteStore
        .getState()
        .creditNotes.filter((c) => c.journalEntryId === entryId)
        .map((c) => ownedBySource('Credit note', 'credit-notes', c.id, `credit note ${c.creditNoteNumber ?? c.id}`)),
  },
  {
    id: 'inventory-costing',
    describes: 'Stock movements and inventory valuation',
    probe: (entryId) =>
      useInventoryStore
        .getState()
        .movements.filter((m) => m.journalEntryId === entryId)
        .map((m) =>
          derivedRecord(
            'inventory_costing',
            'Stock movement',
            m.id,
            `Stock movement ${m.id}`,
            'Inventory valuation was computed from this posting, so the entry must be reversed rather than rewritten.',
          ),
        ),
  },
  {
    id: 'fixed-assets',
    describes: 'Asset transactions and finalized depreciation runs',
    probe: (entryId) => {
      const state = useFixedAssetStore.getState();
      const found: JournalDependency[] = [];
      for (const t of state.transactions ?? []) {
        if (t.journalEntryId === entryId) {
          found.push(ownedBySource('Fixed asset transaction', 'fixed-assets', t.id, `fixed-asset transaction ${t.id}`));
        }
      }
      for (const run of state.runs ?? []) {
        if (run.journalEntryId === entryId || run.reversalJournalEntryId === entryId) {
          found.push(
            ownedBySource('Depreciation run', 'fixed-assets', run.id, `depreciation run ${run.id}`),
          );
        }
      }
      return found;
    },
  },
  {
    id: 'journal-voucher',
    describes: 'Journal vouchers that posted this entry',
    probe: (entryId) =>
      useJournalVoucherStore
        .getState()
        .vouchers.filter((v) => v.journalEntryId === entryId)
        .map((v) => ownedBySource('Journal voucher', 'journal-vouchers', v.id, `journal voucher ${v.number || v.id}`)),
  },
  {
    id: 'bank-reconciliation',
    describes: 'Bank reconciliation (module not present in this deployment)',
    /*
     * Registered deliberately. Ledgora has no bank-reconciliation module, so
     * this can only return nothing today — but the probe existing is what makes
     * "no reconciliation dependency" a checked answer rather than an
     * unasked question, and gives the future module one obvious place to land.
     */
    probe: () => [],
  },
  {
    id: 'payroll',
    describes: 'Payroll subsystem (module not present in this deployment)',
    probe: () => [],
  },
];

/** Every dependency on an entry, from every registered probe. */
export function collectDependencies(entryId: string, entryDate: string): JournalDependency[] {
  return DEPENDENCY_PROBES.flatMap((p) => {
    try {
      return p.probe(entryId, entryDate);
    } catch {
      /*
       * A probe that throws must not be read as "no dependency". Report it as a
       * blocker: an unanswerable question about whether something depends on
       * this entry is not permission to overwrite it.
       */
      return [
        {
          kind: 'downstream_record' as const,
          severity: 'blocks' as const,
          sourceType: 'Dependency check',
          sourceId: p.id,
          sourceLabel: p.describes,
          message: `The "${p.describes}" dependency check could not be completed, so this entry cannot be corrected safely right now.`,
        },
      ];
    }
  });
}
