import type { Account, BusinessEntity } from '@/types';
import type { Invoice } from '@/types/invoice';
import type { CreditNote } from '@/types/creditNote';
import type { Receipt } from '@/types/receipt';
import type { JournalEntry } from '@/types/journal';
import type {
  StatementLine,
  StatementOfAccount,
  StatementOptions,
  StatementCurrencyMode,
} from '@/types/statementOfAccount';
import { CREDIT_NOTE_REASON_LABELS } from '@/lib/creditNoteLabels';
import { RECEIPT_METHOD_LABELS } from '@/lib/receiptLabels';
import { calculateCustomerUnappliedReceipts } from '@/lib/receiptAllocations';
import { buildOutstandingInvoiceSchedule, calculateAgingSummary } from '@/lib/statementAging';
import { calculateCustomerOpeningBalance } from '@/lib/statementOpeningBalance';
import { calculateCustomerSubledgerBalance, validateStatementReconciliation } from '@/lib/statementReconciliation';
import { roundMoney, BALANCE_TOLERANCE } from '@/lib/journalValidation';
import { generateId, nowIso } from '@/lib/utils';

/* ─────────────────────────── Shared selectors ───────────────────────────── */

/** The customer's receivable control account id (their own, else the 1221 default). */
export function customerReceivableAccountId(customer: BusinessEntity | undefined, accounts: Account[]): string {
  return customer?.defaultReceivableAccount || accounts.find((a) => a.code === '1221')?.id || '';
}

const ISSUED_INVOICE = (i: Invoice): boolean => i.status !== 'draft' && i.status !== 'void';
const APPLIED_CREDIT = (c: CreditNote): boolean => c.status === 'issued' || c.status === 'applied' || c.status === 'partially-applied';
const POSTED_RECEIPT = (r: Receipt): boolean => r.status === 'posted' || r.status === 'partially-allocated' || r.status === 'fully-allocated';
const RECEIVABLE_RECEIPT = (r: Receipt): boolean => r.receiptType === 'customer-payment' || r.receiptType === 'unapplied-customer-receipt';

/** Journal entries generated BY documents — excluded from "manual" adjustments to avoid double counting. */
export function collectLinkedJournalIds(invoices: Invoice[], creditNotes: CreditNote[], receipts: Receipt[]): Set<string> {
  const ids = new Set<string>();
  const add = (id?: string) => { if (id) ids.add(id); };
  for (const i of invoices) { add(i.journalEntryId); add(i.reversalJournalEntryId); }
  for (const c of creditNotes) { add(c.journalEntryId); add(c.reversalJournalEntryId); add(c.inventoryJournalEntryId); for (const r of c.refunds) add(r.journalEntryId); }
  for (const r of receipts) { add(r.journalEntryId); add(r.reversalJournalEntryId); }
  return ids;
}

export interface StatementBuildInput {
  entityId: string;
  customerId: string;
  options: StatementOptions;
  invoices: Invoice[];
  creditNotes: CreditNote[];
  receipts: Receipt[];
  journalEntries: JournalEntry[];
  customers: BusinessEntity[];
  accounts: Account[];
  baseCurrency: string;
}

/* ─────────────────────── Currency-aware amount helper ────────────────────── */

function convert(native: number, rate: number, mode: StatementCurrencyMode): number {
  if (mode === 'single-currency') return roundMoney(native);
  return roundMoney(native * (rate || 1)); // base-currency / multi-currency → historical base
}

/* ───────────────────────── Raw receivable events ─────────────────────────── */

/**
 * Every receivable-affecting event for the customer (invoices as debits; credit
 * notes, receipts, refunds and unlinked manual journals as their real effect),
 * across ALL dates. No running balance yet. The invoice line keeps its ORIGINAL
 * total — later credits/receipts appear as their own lines.
 */
export function buildAllStatementLines(input: StatementBuildInput, receivableAccountId: string): StatementLine[] {
  const { customerId, entityId, options } = input;
  const mode = options.currencyMode;
  const single = mode === 'single-currency';
  const cur = options.currency;
  const lines: StatementLine[] = [];

  const matches = (docEntity: string, docCustomer: string, docCurrency: string): boolean =>
    docEntity === entityId && docCustomer === customerId && (!single || docCurrency === cur);

  // Invoices → debit (original grand total).
  for (const inv of input.invoices) {
    if (!ISSUED_INVOICE(inv) || !matches(inv.entityId, inv.customerId, inv.currency)) continue;
    lines.push({
      id: generateId('stmt'), type: 'invoice', date: inv.issueDate, postingDate: inv.issuedAt?.slice(0, 10), dueDate: inv.dueDate,
      documentNumber: inv.invoiceNumber, reference: inv.purchaseOrderReference, description: `Invoice ${inv.invoiceNumber}`,
      debit: convert(inv.grandTotal, inv.exchangeRate, mode), credit: 0, runningBalance: 0,
      currency: inv.currency, baseCurrencyAmount: roundMoney(inv.grandTotal * (inv.exchangeRate || 1)),
      invoiceId: inv.id, journalEntryId: inv.journalEntryId, status: inv.status,
    });
  }

  // Credit notes → credit (amount posted to receivables = grand total).
  for (const cn of input.creditNotes) {
    if (!APPLIED_CREDIT(cn) || !matches(cn.entityId, cn.customerId, cn.currency)) continue;
    lines.push({
      id: generateId('stmt'), type: 'credit-note', date: cn.issueDate, documentNumber: cn.creditNoteNumber,
      reference: cn.originalInvoiceNumber, description: `Credit note ${cn.creditNoteNumber} — ${CREDIT_NOTE_REASON_LABELS[cn.reasonCode]}`,
      debit: 0, credit: convert(cn.grandTotal, cn.exchangeRate, mode), runningBalance: 0,
      currency: cn.currency, baseCurrencyAmount: roundMoney(cn.grandTotal * (cn.exchangeRate || 1)),
      creditNoteId: cn.id, invoiceId: cn.originalInvoiceId, journalEntryId: cn.journalEntryId, status: cn.status,
    });

    // Refunds on the credit note → debit (Dr receivables / Cr bank).
    for (const rf of cn.refunds) {
      lines.push({
        id: generateId('stmt'), type: 'refund', date: rf.refundDate, documentNumber: rf.reference || cn.creditNoteNumber,
        description: `Refund of ${cn.creditNoteNumber}`, debit: convert(rf.amount, cn.exchangeRate, mode), credit: 0, runningBalance: 0,
        currency: cn.currency, baseCurrencyAmount: roundMoney(rf.amount * (cn.exchangeRate || 1)),
        creditNoteId: cn.id, journalEntryId: rf.journalEntryId, status: 'refunded',
      });
    }
  }

  // Receipts → credit (amount posted to receivables). Customer advances hit a
  // liability account, so they are NOT receivable lines (shown in the summary).
  for (const r of input.receipts) {
    if (!POSTED_RECEIPT(r) || !RECEIVABLE_RECEIPT(r) || !matches(r.entityId, r.customerId ?? '', r.currency)) continue;
    lines.push({
      id: generateId('stmt'), type: 'receipt', date: r.receiptDate, postingDate: r.postedAt?.slice(0, 10),
      documentNumber: r.receiptNumber, reference: r.transactionReference, description: `Receipt ${r.receiptNumber} · ${RECEIPT_METHOD_LABELS[r.method]}`,
      debit: 0, credit: convert(r.amount, r.exchangeRate, mode), runningBalance: 0,
      currency: r.currency, baseCurrencyAmount: roundMoney(r.amount * (r.exchangeRate || 1)),
      receiptId: r.id, journalEntryId: r.journalEntryId, status: r.status,
      allocations: r.allocations.filter((a) => !a.reversed && a.invoiceId).map((a) => ({ label: `Applied to ${a.invoiceNumber ?? 'invoice'}`, invoiceId: a.invoiceId, invoiceNumber: a.invoiceNumber, amount: a.amount })),
    });
  }

  // Unlinked manual journal adjustments hitting the customer's receivable line.
  const linked = collectLinkedJournalIds(input.invoices, input.creditNotes, input.receipts);
  for (const entry of input.journalEntries) {
    if (entry.status !== 'posted' || linked.has(entry.id)) continue;
    if (single && entry.currency !== cur) continue;
    for (const line of entry.lines) {
      if (line.accountId !== receivableAccountId || line.entityId !== customerId) continue;
      if ((Number(line.debit) || 0) === 0 && (Number(line.credit) || 0) === 0) continue;
      const isReversal = !!entry.originalEntryId;
      lines.push({
        id: generateId('stmt'), type: isReversal ? 'reversal' : 'journal-adjustment', date: entry.entryDate, postingDate: entry.postedAt?.slice(0, 10),
        documentNumber: entry.entryNumber, reference: entry.reference, description: entry.description || line.memo || 'Journal adjustment',
        debit: convert(Number(line.debit) || 0, entry.exchangeRate, mode), credit: convert(Number(line.credit) || 0, entry.exchangeRate, mode), runningBalance: 0,
        currency: entry.currency, baseCurrencyAmount: roundMoney(((Number(line.debit) || 0) - (Number(line.credit) || 0)) * (entry.exchangeRate || 1)),
        journalEntryId: entry.id, status: 'posted',
      });
    }
  }

  return lines;
}

/** Defensive dedup: drop any journal-adjustment/reversal line that references a document-generated journal. */
export function deduplicateStatementEvents(lines: StatementLine[], linkedJournalIds: Set<string>): StatementLine[] {
  return lines.filter((l) => {
    if (l.type !== 'journal-adjustment' && l.type !== 'reversal') return true;
    return !(l.journalEntryId && linkedJournalIds.has(l.journalEntryId));
  });
}

/** Chronological order: date, then opening→debits→credits, then posting date, then document number. */
export function sortStatementLines(lines: StatementLine[]): StatementLine[] {
  const rank = (l: StatementLine): number => (l.type === 'opening-balance' ? 0 : l.debit > 0 ? 1 : 2);
  return [...lines].sort(
    (a, b) =>
      a.date.localeCompare(b.date) ||
      rank(a) - rank(b) ||
      (a.postingDate ?? '').localeCompare(b.postingDate ?? '') ||
      (a.documentNumber ?? '').localeCompare(b.documentNumber ?? ''),
  );
}

/** Assign running balances starting from `startingBalance` (chronological). */
export function calculateRunningBalances(lines: StatementLine[], startingBalance: number): StatementLine[] {
  let bal = roundMoney(startingBalance);
  return lines.map((l) => {
    if (l.type === 'opening-balance') { l.runningBalance = bal; return l; }
    bal = roundMoney(bal + (Number(l.debit) || 0) - (Number(l.credit) || 0));
    return { ...l, runningBalance: bal };
  });
}

export interface StatementTotals { periodDebits: number; periodCredits: number; }
export function calculateStatementTotals(periodLines: StatementLine[]): StatementTotals {
  let periodDebits = 0;
  let periodCredits = 0;
  for (const l of periodLines) { periodDebits += Number(l.debit) || 0; periodCredits += Number(l.credit) || 0; }
  return { periodDebits: roundMoney(periodDebits), periodCredits: roundMoney(periodCredits) };
}

/* ───────────────────────────── Main builder ─────────────────────────────── */

export function buildStatementOfAccount(input: StatementBuildInput): StatementOfAccount {
  const { customerId, entityId, options, baseCurrency } = input;
  const customer = input.customers.find((c) => c.id === customerId);
  const receivableAccountId = customerReceivableAccountId(customer, input.accounts);
  const mode = options.currencyMode;
  const statementCurrency = mode === 'single-currency' ? options.currency : baseCurrency;
  const warnings: string[] = [];

  if (!customer) warnings.push('Customer record not found — some statement metadata is unavailable.');
  if (!receivableAccountId) warnings.push('No receivable control account is mapped for this customer; reconciliation may be unavailable.');

  const linkedIds = collectLinkedJournalIds(input.invoices, input.creditNotes, input.receipts);
  const allLines = deduplicateStatementEvents(buildAllStatementLines(input, receivableAccountId), linkedIds);

  // Multi-currency: converting to base — warn if more than one native currency is present.
  const nativeCurrencies = new Set(allLines.map((l) => l.currency));
  if (mode === 'multi-currency' && nativeCurrencies.size > 1) {
    warnings.push(`Multiple currencies present (${[...nativeCurrencies].join(', ')}); amounts are converted to ${baseCurrency} at each transaction's stored rate.`);
  }
  if (mode !== 'single-currency') {
    for (const l of allLines) if (l.baseCurrencyAmount === undefined) warnings.push('Some transactions are missing exchange-rate information.');
  }

  const activityOnly = options.statementType === 'activity-only';
  const openItem = options.statementType === 'open-item';
  const openingBalance = activityOnly || openItem ? 0 : calculateCustomerOpeningBalance(allLines, options.periodStart);

  // Customer-facing filtered documents for aging / outstanding / advances.
  const custInvoices = input.invoices.filter((i) => ISSUED_INVOICE(i) && i.entityId === entityId && i.customerId === customerId && (mode !== 'single-currency' || i.currency === statementCurrency));
  const schedule = buildOutstandingInvoiceSchedule(custInvoices, input.creditNotes, input.receipts, options.periodEnd, { includeSettled: options.includeSettledInvoices });
  const aging = calculateAgingSummary(schedule, options.asOfDate);
  const overdueAmount = roundMoney(aging.buckets.filter((b) => b.id !== 'current').reduce((s, b) => s + b.amount, 0));
  const custReceipts = input.receipts.filter((r) => r.customerId === customerId && (mode !== 'single-currency' || r.currency === statementCurrency));
  const { unappliedReceipts, advances } = calculateCustomerUnappliedReceipts(customerId, custReceipts);

  // Build displayed lines + totals per statement type.
  let displayLines: StatementLine[];
  let periodDebits: number;
  let periodCredits: number;
  let closingBalance: number;

  if (openItem) {
    // Open-item ledger: current open invoice balances + available customer credit.
    const openLines: StatementLine[] = schedule
      .filter((r) => r.outstandingBalance > BALANCE_TOLERANCE)
      .map((r) => ({
        id: generateId('stmt'), type: 'invoice', date: r.invoiceDate, dueDate: r.dueDate, documentNumber: r.invoiceNumber,
        description: `Invoice ${r.invoiceNumber} (outstanding)`, debit: r.outstandingBalance, credit: 0, runningBalance: 0,
        currency: r.currency, invoiceId: r.invoiceId, status: r.status, daysOverdue: r.daysOverdue, isOverdue: r.daysOverdue > 0,
      }));
    const credit = roundMoney(unappliedReceipts + advances);
    if (options.includeUnappliedReceipts && credit > BALANCE_TOLERANCE) {
      openLines.push({ id: generateId('stmt'), type: 'receipt', date: options.periodEnd, documentNumber: 'Customer credit', description: 'Unapplied receipts & advances', debit: 0, credit, runningBalance: 0, currency: statementCurrency });
    }
    displayLines = calculateRunningBalances(sortStatementLines(openLines), 0);
    const t = calculateStatementTotals(displayLines);
    periodDebits = t.periodDebits; periodCredits = t.periodCredits;
    closingBalance = roundMoney(periodDebits - periodCredits);
  } else {
    const periodLines = sortStatementLines(allLines.filter((l) => l.date >= options.periodStart && l.date <= options.periodEnd));
    const withOpening: StatementLine[] = activityOnly
      ? periodLines
      : [{ id: generateId('stmt'), type: 'opening-balance', date: options.periodStart, description: 'Opening balance', debit: 0, credit: 0, runningBalance: openingBalance, currency: statementCurrency }, ...periodLines];
    displayLines = calculateRunningBalances(withOpening, openingBalance);
    const t = calculateStatementTotals(periodLines);
    periodDebits = t.periodDebits; periodCredits = t.periodCredits;
    closingBalance = roundMoney(openingBalance + periodDebits - periodCredits);
  }

  // Reconcile the calculated closing against the posted journal subledger.
  const subledgerBalance = calculateCustomerSubledgerBalance({ journalEntries: input.journalEntries, receivableAccountId, customerId, asOfDate: options.periodEnd, currencyMode: mode, currency: statementCurrency });
  const recon = openItem
    ? { difference: 0, isReconciled: true, warnings: [] as string[] } // open-item is a snapshot, not a period ledger
    : validateStatementReconciliation(closingBalance, subledgerBalance);
  warnings.push(...recon.warnings);

  const address = customer ? [customer.addressLine1, customer.addressLine2, customer.city, customer.country, customer.postalCode].filter(Boolean).join(', ') : undefined;

  return {
    entityId,
    customerId,
    customerName: customer?.legalName ?? 'Unknown customer',
    customerCode: customer?.entityCode ?? '',
    billingAddress: address || undefined,
    taxNumber: customer?.taxRegistrationNumber || undefined,
    statementType: options.statementType,
    statementBasis: options.statementBasis,
    periodStart: options.periodStart,
    periodEnd: options.periodEnd,
    asOfDate: options.asOfDate,
    currencyMode: mode,
    currency: statementCurrency,
    baseCurrency,
    openingBalance,
    periodDebits,
    periodCredits,
    closingBalance,
    unappliedReceipts,
    customerAdvances: advances,
    availableCredit: roundMoney(unappliedReceipts + advances),
    overdueAmount,
    lines: displayLines,
    aging,
    outstandingInvoices: schedule,
    subledgerBalance,
    reconciliationDifference: recon.difference,
    isReconciled: recon.isReconciled,
    warnings,
    generatedAt: nowIso(),
  };
}
