import { sql } from 'kysely';
type AnyKysely = import('kysely').Kysely<any>;

export async function up(db: AnyKysely): Promise<void> {
  await sql`ALTER TABLE organizations ADD COLUMN subscriber_owner_user_id uuid`.execute(db);
  await sql`DO $$ BEGIN IF EXISTS (SELECT o.id FROM organizations o LEFT JOIN organization_memberships m ON m.organization_id=o.id AND m.role='owner' AND m.status='active' GROUP BY o.id HAVING count(m.id)<>1) THEN RAISE EXCEPTION 'Every existing workspace must have exactly one active subscriber owner'; END IF; END $$`.execute(db);
  await sql`UPDATE organizations o SET subscriber_owner_user_id=m.user_id FROM organization_memberships m WHERE m.organization_id=o.id AND m.role='owner' AND m.status='active'`.execute(db);
  await sql`ALTER TABLE organizations ALTER COLUMN subscriber_owner_user_id SET NOT NULL`.execute(db);
  await sql`ALTER TABLE organizations ADD CONSTRAINT organizations_subscriber_owner_fk FOREIGN KEY (subscriber_owner_user_id) REFERENCES users(id) ON DELETE RESTRICT`.execute(db);
  await sql`CREATE UNIQUE INDEX organizations_subscriber_owner_unique ON organizations(subscriber_owner_user_id)`.execute(db);
  await sql`CREATE UNIQUE INDEX organization_memberships_one_owner ON organization_memberships(organization_id) WHERE role='owner'`.execute(db);
  await sql`CREATE TABLE subscriber_workspace_ownership_claims (workspace_id uuid PRIMARY KEY, subscriber_owner_user_id uuid NOT NULL UNIQUE, claimed_at timestamptz NOT NULL DEFAULT now(), retired_at timestamptz)`.execute(db);
  await sql`INSERT INTO subscriber_workspace_ownership_claims (workspace_id, subscriber_owner_user_id) SELECT id, subscriber_owner_user_id FROM organizations`.execute(db);
  await sql`CREATE FUNCTION protect_subscriber_ownership() RETURNS trigger AS $$ DECLARE designated uuid; retired timestamptz; BEGIN IF TG_TABLE_NAME='organizations' THEN IF TG_OP='INSERT' THEN INSERT INTO subscriber_workspace_ownership_claims (workspace_id,subscriber_owner_user_id) VALUES (NEW.id,NEW.subscriber_owner_user_id) ON CONFLICT DO NOTHING; SELECT subscriber_owner_user_id,retired_at INTO designated,retired FROM subscriber_workspace_ownership_claims WHERE workspace_id=NEW.id; IF designated IS DISTINCT FROM NEW.subscriber_owner_user_id OR retired IS NOT NULL THEN RAISE EXCEPTION 'Subscriber workspace ownership cannot be assigned or recycled' USING ERRCODE='23514'; END IF; RETURN NEW; ELSIF TG_OP='UPDATE' THEN IF NEW.subscriber_owner_user_id IS DISTINCT FROM OLD.subscriber_owner_user_id THEN RAISE EXCEPTION 'Subscriber workspace ownership is immutable' USING ERRCODE='23514'; END IF; RETURN NEW; ELSE SELECT retired_at INTO retired FROM subscriber_workspace_ownership_claims WHERE workspace_id=OLD.id AND subscriber_owner_user_id=OLD.subscriber_owner_user_id; IF retired IS NULL THEN RAISE EXCEPTION 'Subscriber workspace ownership cannot be released' USING ERRCODE='23514'; END IF; RETURN OLD; END IF; END IF; IF TG_OP<>'INSERT' AND OLD.role='owner' THEN IF TG_OP='DELETE' THEN SELECT retired_at INTO retired FROM subscriber_workspace_ownership_claims WHERE workspace_id=OLD.organization_id AND subscriber_owner_user_id=OLD.user_id; IF retired IS NULL THEN RAISE EXCEPTION 'Subscriber owner membership is immutable' USING ERRCODE='23514'; END IF; RETURN OLD; END IF; IF NEW.user_id IS DISTINCT FROM OLD.user_id OR NEW.organization_id IS DISTINCT FROM OLD.organization_id OR NEW.role<>'owner' OR NEW.status<>'active' THEN RAISE EXCEPTION 'Subscriber owner membership is immutable' USING ERRCODE='23514'; END IF; END IF; IF TG_OP<>'DELETE' AND NEW.role='owner' THEN SELECT subscriber_owner_user_id INTO designated FROM organizations WHERE id=NEW.organization_id; IF designated IS NULL OR designated<>NEW.user_id OR NEW.status<>'active' THEN RAISE EXCEPTION 'Only the designated subscriber may hold the owner membership' USING ERRCODE='23514'; END IF; END IF; IF TG_OP='DELETE' THEN RETURN OLD; END IF; RETURN NEW; END; $$ LANGUAGE plpgsql`.execute(db);
  await sql`CREATE TRIGGER organizations_immutable_subscriber_owner BEFORE INSERT OR UPDATE OF subscriber_owner_user_id OR DELETE ON organizations FOR EACH ROW EXECUTE FUNCTION protect_subscriber_ownership()`.execute(db);
  await sql`CREATE TRIGGER memberships_immutable_subscriber_owner BEFORE INSERT OR UPDATE OR DELETE ON organization_memberships FOR EACH ROW EXECUTE FUNCTION protect_subscriber_ownership()`.execute(db);
  await sql`CREATE FUNCTION protect_subscriber_ownership_claim() RETURNS trigger AS $$ BEGIN IF TG_OP='DELETE' OR NEW.workspace_id IS DISTINCT FROM OLD.workspace_id OR NEW.subscriber_owner_user_id IS DISTINCT FROM OLD.subscriber_owner_user_id OR NEW.claimed_at IS DISTINCT FROM OLD.claimed_at OR OLD.retired_at IS NOT NULL OR NEW.retired_at IS NULL THEN RAISE EXCEPTION 'Subscriber workspace ownership claims are permanent' USING ERRCODE='23514'; END IF; RETURN NEW; END; $$ LANGUAGE plpgsql`.execute(db);
  await sql`CREATE TRIGGER immutable_subscriber_ownership_claim BEFORE UPDATE OR DELETE ON subscriber_workspace_ownership_claims FOR EACH ROW EXECUTE FUNCTION protect_subscriber_ownership_claim()`.execute(db);
  await sql`CREATE FUNCTION assert_workspace_has_one_subscriber_owner() RETURNS trigger AS $$ DECLARE workspace_id uuid; designated uuid; matches integer; BEGIN IF TG_TABLE_NAME='organizations' THEN workspace_id:=NEW.id; ELSIF TG_OP='DELETE' THEN workspace_id:=OLD.organization_id; ELSE workspace_id:=NEW.organization_id; END IF; SELECT subscriber_owner_user_id INTO designated FROM organizations WHERE id=workspace_id; IF designated IS NULL THEN RETURN NULL; END IF; SELECT count(*) INTO matches FROM organization_memberships WHERE organization_id=workspace_id AND user_id=designated AND role='owner' AND status='active'; IF matches<>1 THEN RAISE EXCEPTION 'A subscriber workspace must have exactly one immutable owner' USING ERRCODE='23514'; END IF; RETURN NULL; END; $$ LANGUAGE plpgsql`.execute(db);
  await sql`CREATE CONSTRAINT TRIGGER workspace_owner_after_organization AFTER INSERT OR UPDATE ON organizations DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION assert_workspace_has_one_subscriber_owner()`.execute(db);
  await sql`CREATE CONSTRAINT TRIGGER workspace_owner_after_membership AFTER INSERT OR UPDATE OR DELETE ON organization_memberships DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION assert_workspace_has_one_subscriber_owner()`.execute(db);
}

export async function down(db: AnyKysely): Promise<void> {
  await sql`DROP TRIGGER IF EXISTS workspace_owner_after_membership ON organization_memberships`.execute(db);
  await sql`DROP TRIGGER IF EXISTS workspace_owner_after_organization ON organizations`.execute(db);
  await sql`DROP FUNCTION IF EXISTS assert_workspace_has_one_subscriber_owner()`.execute(db);
  await sql`DROP TRIGGER IF EXISTS immutable_subscriber_ownership_claim ON subscriber_workspace_ownership_claims`.execute(db);
  await sql`DROP FUNCTION IF EXISTS protect_subscriber_ownership_claim()`.execute(db);
  await sql`DROP TRIGGER IF EXISTS memberships_immutable_subscriber_owner ON organization_memberships`.execute(db);
  await sql`DROP TRIGGER IF EXISTS organizations_immutable_subscriber_owner ON organizations`.execute(db);
  await sql`DROP FUNCTION IF EXISTS protect_subscriber_ownership()`.execute(db);
  await sql`DROP TABLE IF EXISTS subscriber_workspace_ownership_claims`.execute(db);
  await sql`DROP INDEX IF EXISTS organization_memberships_one_owner`.execute(db);
  await sql`DROP INDEX IF EXISTS organizations_subscriber_owner_unique`.execute(db);
  await sql`ALTER TABLE organizations DROP CONSTRAINT IF EXISTS organizations_subscriber_owner_fk`.execute(db);
  await sql`ALTER TABLE organizations DROP COLUMN IF EXISTS subscriber_owner_user_id`.execute(db);
}
