/**
 * The single Ledgora module registry. Every gate-able capability is declared
 * here once, with its dependencies and the editions that include it by default.
 *
 * Edition nesting (Projects ⊃ Core, Construction ⊃ Projects) is expressed by
 * listing every edition a module belongs to in `defaultForEditions`. The
 * Enterprise preset is derived separately as "all stable modules" so newly
 * added stable modules are automatically included.
 *
 * This file must NOT import editions.ts (which reads this registry) to avoid a
 * circular runtime constant.
 */
import type { LedgoraModule, ModuleDefinition } from '@/types/entitlements';

/** Convenience: editions that inherit Core (every edition includes Core). */
const CORE_TIER = [
  'core',
  'projects',
  'construction',
  'manufacturing',
  'enterprise',
] as const;
const PROJECTS_TIER = ['projects', 'construction', 'enterprise'] as const;
const CONSTRUCTION_TIER = ['construction', 'enterprise'] as const;
const MANUFACTURING_TIER = ['manufacturing', 'enterprise'] as const;
/** Cost centers ship with both the Projects tier and Manufacturing. */
const COST_CENTER_EDITIONS = [
  'projects',
  'construction',
  'manufacturing',
  'enterprise',
] as const;

export const MODULE_DEFINITIONS: ModuleDefinition[] = [
  /* ── Core accounting ──────────────────────────────────────────────────── */
  {
    id: 'core_accounting',
    name: 'Core Accounting',
    description: 'Chart of accounts, general journal, ledger and financial statements.',
    category: 'core',
    dependencies: [],
    defaultForEditions: [...CORE_TIER],
    isVisibleInAdmin: true,
  },
  {
    id: 'sales',
    name: 'Sales',
    description: 'Customers, invoices, credit notes and receipts.',
    category: 'sales',
    dependencies: ['core_accounting'],
    defaultForEditions: [...CORE_TIER],
    isVisibleInAdmin: true,
  },
  {
    id: 'purchases',
    name: 'Purchases',
    description: 'Suppliers, bills, supplier credits and payments.',
    category: 'purchases',
    dependencies: ['core_accounting'],
    defaultForEditions: [...CORE_TIER],
    isVisibleInAdmin: true,
  },
  {
    id: 'customer_statements',
    name: 'Customer Statements',
    description: 'Customer statements of account.',
    category: 'sales',
    dependencies: ['sales'],
    defaultForEditions: [...CORE_TIER],
    isVisibleInAdmin: true,
  },
  {
    id: 'supplier_statements',
    name: 'Supplier Statements',
    description: 'Supplier statements of account.',
    category: 'purchases',
    dependencies: ['purchases'],
    defaultForEditions: [...CORE_TIER],
    isVisibleInAdmin: true,
  },
  {
    id: 'tax_basic',
    name: 'Basic Tax',
    description: 'VAT / sales-tax codes and standard tax reporting.',
    category: 'core',
    dependencies: ['core_accounting'],
    defaultForEditions: [...CORE_TIER],
    isVisibleInAdmin: true,
  },
  {
    id: 'currency_basic',
    name: 'Basic Currencies',
    description: 'Multi-currency master data and exchange rates.',
    category: 'core',
    dependencies: ['core_accounting'],
    defaultForEditions: [...CORE_TIER],
    isVisibleInAdmin: true,
  },
  {
    id: 'fixed_assets',
    name: 'Fixed Assets',
    description: 'Asset register, depreciation, transfers, impairment, revaluation and disposals with automatic journal vouchers.',
    category: 'core',
    dependencies: ['core_accounting'],
    defaultForEditions: [...CORE_TIER],
    isVisibleInAdmin: true,
  },

  /* ── Advanced core (Enterprise) ───────────────────────────────────────── */
  {
    id: 'tax_advanced',
    name: 'Advanced Tax',
    description: 'Tax groups, jurisdictions, periods and reconciliation.',
    category: 'reporting',
    dependencies: ['tax_basic'],
    defaultForEditions: ['enterprise'],
    isVisibleInAdmin: true,
  },
  {
    id: 'currency_advanced',
    name: 'Advanced Currencies',
    description: 'Period-end revaluation and realized/unrealized FX reporting.',
    category: 'reporting',
    dependencies: ['currency_basic'],
    defaultForEditions: ['enterprise'],
    isVisibleInAdmin: true,
  },

  /* ── Cost centers (Projects tier) ─────────────────────────────────────── */
  {
    id: 'cost_centers',
    name: 'Cost Centers',
    description: 'Cost-center hierarchy, posting rules and reports.',
    category: 'projects',
    dependencies: ['core_accounting'],
    defaultForEditions: [...COST_CENTER_EDITIONS],
    isVisibleInAdmin: true,
  },
  {
    id: 'cost_center_budgets',
    name: 'Cost Center Budgets',
    description: 'Monthly cost-center budgets and budget-vs-actual.',
    category: 'projects',
    dependencies: ['cost_centers'],
    defaultForEditions: [...PROJECTS_TIER],
    isVisibleInAdmin: true,
  },
  {
    id: 'cost_allocations',
    name: 'Cost Allocations',
    description: 'Shared-cost allocation rules and balanced runs.',
    category: 'projects',
    dependencies: ['cost_centers'],
    defaultForEditions: [...PROJECTS_TIER],
    isVisibleInAdmin: true,
  },

  /* ── Projects (Projects tier) ─────────────────────────────────────────── */
  {
    id: 'projects',
    name: 'Projects',
    description: 'Projects, jobs and contracts as accounting dimensions.',
    category: 'projects',
    dependencies: ['core_accounting'],
    defaultForEditions: [...PROJECTS_TIER],
    isVisibleInAdmin: true,
  },
  {
    id: 'project_budgets',
    name: 'Project Budgets',
    description: 'Versioned project budgets and budget-vs-actual.',
    category: 'projects',
    dependencies: ['projects'],
    defaultForEditions: [...PROJECTS_TIER],
    isVisibleInAdmin: true,
  },
  {
    id: 'project_time_expenses',
    name: 'Time & Expenses',
    description: 'Project time entries and expense capture.',
    category: 'projects',
    dependencies: ['projects'],
    defaultForEditions: [...PROJECTS_TIER],
    isVisibleInAdmin: true,
  },
  {
    id: 'project_billing',
    name: 'Project Billing',
    description: 'Bill projects and generate draft invoices.',
    category: 'projects',
    dependencies: ['projects', 'sales'],
    defaultForEditions: [...PROJECTS_TIER],
    isVisibleInAdmin: true,
  },
  {
    id: 'project_profitability',
    name: 'Project Profitability',
    description: 'Revenue, cost and margin by project.',
    category: 'projects',
    dependencies: ['projects'],
    defaultForEditions: [...PROJECTS_TIER],
    isVisibleInAdmin: true,
  },
  {
    id: 'project_cash_flow',
    name: 'Project Cash Flow',
    description: 'Cash in and out attributed to projects.',
    category: 'projects',
    dependencies: ['projects', 'sales', 'purchases'],
    defaultForEditions: [...PROJECTS_TIER],
    isVisibleInAdmin: true,
  },

  /* ── Construction (Construction tier) ─────────────────────────────────── */
  {
    id: 'construction_projects',
    name: 'Construction Projects',
    description: 'Construction project profiles built on the Projects engine.',
    category: 'construction',
    dependencies: ['projects'],
    defaultForEditions: [...CONSTRUCTION_TIER],
    isVisibleInAdmin: true,
  },
  {
    id: 'construction_wbs',
    name: 'Work Breakdown Structure',
    description: 'WBS hierarchy for construction projects.',
    category: 'construction',
    dependencies: ['construction_projects'],
    defaultForEditions: [...CONSTRUCTION_TIER],
    isVisibleInAdmin: true,
  },
  {
    id: 'construction_cost_codes',
    name: 'Cost Codes',
    description: 'Construction cost-code library.',
    category: 'construction',
    dependencies: ['construction_projects'],
    defaultForEditions: [...CONSTRUCTION_TIER],
    isVisibleInAdmin: true,
  },
  {
    id: 'construction_boq',
    name: 'Bill of Quantities',
    description: 'BOQ items and measurement.',
    category: 'construction',
    dependencies: ['construction_projects'],
    defaultForEditions: [...CONSTRUCTION_TIER],
    isVisibleInAdmin: true,
  },
  {
    id: 'construction_progress_billing',
    name: 'Progress Billing',
    description: 'Progress claims and interim certificates.',
    category: 'construction',
    dependencies: ['construction_boq', 'sales'],
    defaultForEditions: [...CONSTRUCTION_TIER],
    isVisibleInAdmin: true,
  },
  {
    id: 'construction_retention',
    name: 'Retention',
    description: 'Retention held and released on progress claims.',
    category: 'construction',
    dependencies: ['construction_projects'],
    defaultForEditions: [...CONSTRUCTION_TIER],
    isVisibleInAdmin: true,
  },
  {
    id: 'construction_subcontracts',
    name: 'Subcontracts',
    description: 'Subcontract agreements and certificates.',
    category: 'construction',
    dependencies: ['construction_projects', 'purchases'],
    defaultForEditions: [...CONSTRUCTION_TIER],
    isVisibleInAdmin: true,
  },
  {
    id: 'construction_variations',
    name: 'Variations',
    description: 'Variation orders and change management.',
    category: 'construction',
    dependencies: ['construction_projects'],
    defaultForEditions: [...CONSTRUCTION_TIER],
    isVisibleInAdmin: true,
  },
  {
    id: 'construction_commitments',
    name: 'Commitments',
    description: 'Committed costs from purchase and subcontract orders.',
    category: 'construction',
    dependencies: ['construction_projects'],
    defaultForEditions: [...CONSTRUCTION_TIER],
    isVisibleInAdmin: true,
  },
  {
    id: 'construction_materials',
    name: 'Materials',
    description: 'Materials tracking against cost codes.',
    category: 'construction',
    // Construction materials build on the shared Inventory engine.
    dependencies: ['construction_projects', 'inventory_basic'],
    defaultForEditions: [...CONSTRUCTION_TIER],
    isVisibleInAdmin: true,
  },
  {
    id: 'construction_labor',
    name: 'Labor',
    description: 'Labor cost tracking against cost codes.',
    category: 'construction',
    dependencies: ['construction_projects'],
    defaultForEditions: [...CONSTRUCTION_TIER],
    isVisibleInAdmin: true,
  },
  {
    id: 'construction_equipment',
    name: 'Equipment',
    description: 'Equipment cost tracking against cost codes.',
    category: 'construction',
    dependencies: ['construction_projects'],
    defaultForEditions: [...CONSTRUCTION_TIER],
    isVisibleInAdmin: true,
  },
  {
    id: 'construction_wip',
    name: 'Work in Progress',
    description: 'Construction WIP and cost accruals.',
    category: 'construction',
    dependencies: ['construction_projects', 'core_accounting'],
    defaultForEditions: [...CONSTRUCTION_TIER],
    isVisibleInAdmin: true,
  },
  {
    id: 'construction_revenue_recognition',
    name: 'Revenue Recognition',
    description: 'Percentage-of-completion revenue recognition.',
    category: 'construction',
    dependencies: ['construction_projects', 'construction_wip'],
    defaultForEditions: [...CONSTRUCTION_TIER],
    isVisibleInAdmin: true,
  },
  {
    id: 'construction_forecasting',
    name: 'Forecast at Completion',
    description: 'Cost and revenue forecast-at-completion.',
    category: 'construction',
    dependencies: ['construction_projects', 'construction_wip'],
    defaultForEditions: [...CONSTRUCTION_TIER],
    isVisibleInAdmin: true,
  },

  /* ── Inventory & warehousing (Manufacturing tier) ─────────────────────── */
  {
    id: 'inventory_basic',
    name: 'Inventory',
    description: 'Stock items, quantities and inventory valuation.',
    category: 'manufacturing',
    dependencies: ['core_accounting'],
    defaultForEditions: [...MANUFACTURING_TIER],
    isVisibleInAdmin: true,
  },
  {
    id: 'inventory_advanced',
    name: 'Advanced Inventory',
    description: 'Transfers, counts and advanced stock movements.',
    category: 'manufacturing',
    dependencies: ['inventory_basic'],
    defaultForEditions: [...MANUFACTURING_TIER],
    isVisibleInAdmin: true,
  },
  {
    id: 'warehouses',
    name: 'Warehouses',
    description: 'Multiple warehouses and stock locations.',
    category: 'manufacturing',
    dependencies: ['inventory_basic'],
    defaultForEditions: [...MANUFACTURING_TIER],
    isVisibleInAdmin: true,
  },
  {
    id: 'lot_serial_tracking',
    name: 'Lot & Serial Tracking',
    description: 'Lot and serial number tracking for inventory.',
    category: 'manufacturing',
    dependencies: ['inventory_basic'],
    defaultForEditions: [...MANUFACTURING_TIER],
    isVisibleInAdmin: true,
  },
  {
    id: 'landed_cost',
    name: 'Landed Cost',
    description: 'Allocate freight, duty and handling into inventory cost.',
    category: 'manufacturing',
    dependencies: ['inventory_basic', 'purchases'],
    defaultForEditions: [...MANUFACTURING_TIER],
    isVisibleInAdmin: true,
  },

  /* ── Manufacturing (Manufacturing tier) ───────────────────────────────── */
  {
    id: 'manufacturing_core',
    name: 'Manufacturing Core',
    description: 'Plants, manufacturing profile and shared production data.',
    category: 'manufacturing',
    dependencies: ['core_accounting', 'inventory_basic', 'warehouses', 'cost_centers'],
    defaultForEditions: [...MANUFACTURING_TIER],
    isVisibleInAdmin: true,
  },
  {
    id: 'manufacturing_items',
    name: 'Manufacturing Items',
    description: 'Raw materials, components, sub-assemblies and finished goods.',
    category: 'manufacturing',
    dependencies: ['manufacturing_core', 'inventory_basic'],
    defaultForEditions: [...MANUFACTURING_TIER],
    isVisibleInAdmin: true,
  },
  {
    id: 'manufacturing_bom',
    name: 'Bills of Materials',
    description: 'Multi-level, versioned bills of materials.',
    category: 'manufacturing',
    dependencies: ['manufacturing_items'],
    defaultForEditions: [...MANUFACTURING_TIER],
    isVisibleInAdmin: true,
  },
  {
    id: 'manufacturing_routings',
    name: 'Routings',
    description: 'Production operations and standard times.',
    category: 'manufacturing',
    dependencies: ['manufacturing_core'],
    defaultForEditions: [...MANUFACTURING_TIER],
    isVisibleInAdmin: true,
  },
  {
    id: 'manufacturing_work_centers',
    name: 'Work Centers',
    description: 'Machines, lines and labor groups with cost rates.',
    category: 'manufacturing',
    dependencies: ['manufacturing_core', 'cost_centers'],
    defaultForEditions: [...MANUFACTURING_TIER],
    isVisibleInAdmin: true,
  },
  {
    id: 'manufacturing_work_orders',
    name: 'Work Orders',
    description: 'Production orders through the plan-to-complete workflow.',
    category: 'manufacturing',
    dependencies: [
      'manufacturing_bom',
      'manufacturing_routings',
      'manufacturing_work_centers',
      'inventory_basic',
      'warehouses',
    ],
    defaultForEditions: [...MANUFACTURING_TIER],
    isVisibleInAdmin: true,
  },
  {
    id: 'manufacturing_production_planning',
    name: 'Production Planning',
    description: 'Demand, work-order proposals and due-date planning.',
    category: 'manufacturing',
    dependencies: ['manufacturing_work_orders'],
    defaultForEditions: [...MANUFACTURING_TIER],
    isVisibleInAdmin: true,
  },
  {
    id: 'manufacturing_mrp',
    name: 'Material Requirements Planning',
    description: 'Net requirements, suggested purchase and work orders.',
    category: 'manufacturing',
    dependencies: ['manufacturing_bom', 'inventory_basic', 'purchases'],
    defaultForEditions: [...MANUFACTURING_TIER],
    isVisibleInAdmin: true,
  },
  {
    id: 'manufacturing_capacity_planning',
    name: 'Capacity Planning',
    description: 'Work-center load and capacity availability.',
    category: 'manufacturing',
    dependencies: ['manufacturing_routings', 'manufacturing_work_centers'],
    defaultForEditions: ['enterprise'],
    isVisibleInAdmin: true,
  },
  {
    id: 'manufacturing_material_issues',
    name: 'Material Issues',
    description: 'Issue raw materials to work orders (Dr WIP / Cr inventory).',
    category: 'manufacturing',
    dependencies: ['manufacturing_work_orders', 'inventory_basic', 'warehouses'],
    defaultForEditions: [...MANUFACTURING_TIER],
    isVisibleInAdmin: true,
  },
  {
    id: 'manufacturing_production_receipts',
    name: 'Production Receipts',
    description: 'Receive finished goods (Dr finished goods / Cr WIP).',
    category: 'manufacturing',
    dependencies: ['manufacturing_work_orders', 'inventory_basic', 'warehouses'],
    defaultForEditions: [...MANUFACTURING_TIER],
    isVisibleInAdmin: true,
  },
  {
    id: 'manufacturing_scrap',
    name: 'Scrap',
    description: 'Record and account for production scrap.',
    category: 'manufacturing',
    dependencies: ['manufacturing_work_orders'],
    defaultForEditions: [...MANUFACTURING_TIER],
    isVisibleInAdmin: true,
  },
  {
    id: 'manufacturing_rework',
    name: 'Rework',
    description: 'Rework work orders and cost treatment.',
    category: 'manufacturing',
    dependencies: ['manufacturing_work_orders'],
    defaultForEditions: ['enterprise'],
    isVisibleInAdmin: true,
  },
  {
    id: 'manufacturing_subcontracting',
    name: 'Subcontract Manufacturing',
    description: 'Send material out and receive subcontracted production.',
    category: 'manufacturing',
    dependencies: ['manufacturing_work_orders', 'purchases'],
    defaultForEditions: ['enterprise'],
    isVisibleInAdmin: true,
  },
  {
    id: 'manufacturing_standard_costing',
    name: 'Standard Costing',
    description: 'Standard product cost from BOM and routing.',
    category: 'manufacturing',
    dependencies: ['manufacturing_bom', 'manufacturing_routings', 'manufacturing_work_centers'],
    defaultForEditions: [...MANUFACTURING_TIER],
    isVisibleInAdmin: true,
  },
  {
    id: 'manufacturing_actual_costing',
    name: 'Actual Costing',
    description: 'Actual work-order cost reconciled to the ledger.',
    category: 'manufacturing',
    dependencies: ['manufacturing_work_orders', 'manufacturing_material_issues', 'manufacturing_production_receipts', 'core_accounting'],
    defaultForEditions: [...MANUFACTURING_TIER],
    isVisibleInAdmin: true,
  },
  {
    id: 'manufacturing_variance_analysis',
    name: 'Variance Analysis',
    description: 'Material, labor, machine, overhead and yield variances.',
    category: 'manufacturing',
    dependencies: ['manufacturing_standard_costing', 'manufacturing_actual_costing'],
    defaultForEditions: [...MANUFACTURING_TIER],
    isVisibleInAdmin: true,
  },
  {
    id: 'manufacturing_quality',
    name: 'Quality',
    description: 'Inspections, holds, non-conformance and corrective action.',
    category: 'manufacturing',
    dependencies: ['manufacturing_work_orders'],
    defaultForEditions: [...MANUFACTURING_TIER],
    isVisibleInAdmin: true,
  },
  {
    id: 'manufacturing_maintenance',
    name: 'Maintenance',
    description: 'Preventive and breakdown maintenance and downtime.',
    category: 'manufacturing',
    dependencies: ['manufacturing_work_centers'],
    defaultForEditions: [...MANUFACTURING_TIER],
    isVisibleInAdmin: true,
  },
  {
    id: 'manufacturing_traceability',
    name: 'Traceability',
    description: 'Lot/serial genealogy from supplier to shipment.',
    category: 'manufacturing',
    dependencies: ['lot_serial_tracking', 'manufacturing_work_orders'],
    defaultForEditions: [...MANUFACTURING_TIER],
    isVisibleInAdmin: true,
  },
  {
    id: 'manufacturing_batch_process',
    name: 'Batch & Process Manufacturing',
    description: 'Formulas, batches and process production.',
    category: 'manufacturing',
    dependencies: ['manufacturing_core'],
    defaultForEditions: ['enterprise'],
    isVisibleInAdmin: true,
  },
  {
    id: 'manufacturing_yield',
    name: 'Yield',
    description: 'Batch yield and loss tracking.',
    category: 'manufacturing',
    dependencies: ['manufacturing_batch_process'],
    defaultForEditions: ['enterprise'],
    isVisibleInAdmin: true,
  },
  {
    id: 'manufacturing_co_products',
    name: 'Co-products & By-products',
    description: 'Co-product and by-product cost allocation.',
    category: 'manufacturing',
    dependencies: ['manufacturing_batch_process'],
    defaultForEditions: ['enterprise'],
    isVisibleInAdmin: true,
  },
  {
    id: 'manufacturing_dashboards',
    name: 'Manufacturing Dashboards',
    description: 'Production, cost and inventory dashboards.',
    category: 'manufacturing',
    dependencies: ['manufacturing_core'],
    defaultForEditions: [...MANUFACTURING_TIER],
    isVisibleInAdmin: true,
  },
  {
    id: 'manufacturing_reports',
    name: 'Manufacturing Reports',
    description: 'Production, costing, variance and inventory reports.',
    category: 'manufacturing',
    dependencies: ['manufacturing_core'],
    defaultForEditions: [...MANUFACTURING_TIER],
    isVisibleInAdmin: true,
  },

  /* ── Administration / future (Enterprise) ─────────────────────────────── */
  {
    id: 'advanced_reporting',
    name: 'Advanced Reporting',
    description: 'Custom and cross-dimensional reporting.',
    category: 'reporting',
    dependencies: ['core_accounting'],
    defaultForEditions: ['enterprise'],
    isVisibleInAdmin: true,
  },
  {
    id: 'multi_entity',
    name: 'Multi-Entity & Consolidation',
    description: 'Multiple entities and consolidated reporting.',
    category: 'administration',
    dependencies: ['core_accounting'],
    defaultForEditions: ['enterprise'],
    isVisibleInAdmin: true,
  },
  {
    id: 'approvals',
    name: 'Approvals',
    description: 'Advanced approval workflows.',
    category: 'administration',
    dependencies: ['core_accounting'],
    defaultForEditions: ['enterprise'],
    isVisibleInAdmin: true,
  },
  {
    id: 'audit_admin',
    name: 'Audit & Administration',
    description: 'Permissions, audit trail and admin services.',
    category: 'administration',
    dependencies: ['core_accounting'],
    defaultForEditions: ['enterprise'],
    isVisibleInAdmin: true,
  },
];

/** Indexed lookup for O(1) access to a module definition. */
export const MODULE_BY_ID: Record<LedgoraModule, ModuleDefinition> =
  Object.fromEntries(MODULE_DEFINITIONS.map((m) => [m.id, m])) as Record<
    LedgoraModule,
    ModuleDefinition
  >;

/** Every module id, in registry order (a stable canonical ordering). */
export const ALL_MODULE_IDS: LedgoraModule[] = MODULE_DEFINITIONS.map((m) => m.id);

/** Position of each module in the canonical ordering (used to sort results). */
export const MODULE_ORDER: Record<LedgoraModule, number> = Object.fromEntries(
  ALL_MODULE_IDS.map((id, i) => [id, i]),
) as Record<LedgoraModule, number>;

/** True when the module exists and is not experimental (eligible for Enterprise). */
export function isStableModule(id: LedgoraModule): boolean {
  return MODULE_BY_ID[id]?.isExperimental !== true;
}

export function getModuleDefinition(id: LedgoraModule): ModuleDefinition | undefined {
  return MODULE_BY_ID[id];
}
